/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cloud_logic_custom": [
        {
            "name": "mwabapi2",
            "endpoint": "https://yotgg8owp1.execute-api.ap-south-1.amazonaws.com/main",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
